import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
 // eslint-disable-next-line camelcase
 import {Inter,Space_Grotesk} from 'next/font/google'
import React from "react";
import { ThemeProvider } from "@/context";
import "./globals.css";
import '../styles/prism.css'
export const metadata: Metadata = {
  title: "DevFlow",
  description: "Generated by create next app",
  icons:{
    icon:"/assets/images/site-logo.svg"
  }
};
const inter=Inter({
  subsets:['latin'],
  weight:['100','200','300','400','500','600','700','800','900'],
  variable:"--font-inter"
})

const spaceGrotesk =Space_Grotesk({
  subsets:['latin'],
  weight:['300','400','500','600','700'],
  variable:"--font-space"
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  

    <html lang="en">
      <body className={`${inter.variable} ${spaceGrotesk.variable}`}>
      <ClerkProvider appearance={
      {
        elements:{
          formButtonPrimary:'primary-gradient',
          footerActionLink:'primary-text-gradient hover:text-primary-500'
        }
      }
    }>
        <ThemeProvider >
        {children}
        </ThemeProvider>
    </ClerkProvider>

        </body>
    </html>


  );
}
